// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efvynopreyliagayqabt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdnlub3ByZXlsaWFnYXlxYWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDUxNjQsImV4cCI6MjA3MjAyMTE2NH0.GE4BLe4NS5rg8BGBbSME_R6ufWM4Y1ytkePR8Q_tom4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});